---
name: morgi-gwyrdd
description: This is just my persoanl fork of bazzite.
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest
modules:
  # Copy files to the image.
  - type: files
    files:
      - source: system
        destination: /

  # Just Files.
  - type: justfiles
    validate: true
    include:
      - morgi-gwyrdd-generic-hostname.just
  
  # Virtualisation Stack.
  - type: rpm-ostree
    install:
      - "virt-install"
      - "libvirt-daemon-config-network"
      - "libvirt-daemon-kvm"
      - "edk2-ovmf"
      - "virt-manager"
      - "virt-viewer"
      - "libguestfs-tools"
      - "python3-libguestfs"
      - "virt-top"
      - "swtpm"
      - "bridge-utils"
      - "gnome-boxes"
      - "cmake"
      - "gcc"
      - "gcc-c++"
      - "libglvnd-devel"
      - "fontconfig-devel"
      - "spice-protocol"
      - "make"
      - "nettle-devel"
      - "pkgconf-pkg-config"
      - "binutils-devel"
      - "libXi-devel"
      - "libXinerama-devel"
      - "libXcursor-devel"
      - "libXpresent-devel"
      - "libxkbcommon-x11-devel"
      - "wayland-devel"
      - "wayland-protocols-devel"
      - "libXScrnSaver-devel"
      - "libXrandr-devel"
      - "dejavu-sans-mono-fonts"
      - "libdecor-devel"
      #- "pipewire-devel"
      - "pulseaudio-libs-devel"
      - "libsamplerate-devel"
      - "go"
  
  - type: script
    snippets:
      # looking-glass
      - "git clone --recursive https://github.com/gnif/LookingGlass.git /opt/io.looking-glass.client"
      - "(cd /opt/io.looking-glass.client/;git checkout $(git describe --tags '$(git rev-list --tags --max-count=1)'))"
      - "mkdir -p /opt/io.looking-glass.client/client/build"
      - "(cd /opt/io.looking-glass.client/client/build;cmake -DENABLE_PIPEWIRE=no -DENABLE_LIBDECOR=ON -DCMAKE_INSTALL_PREFIX=/usr ../)"
      - "(cd /opt/io.looking-glass.client/client/build;make)"
      - "mkdir -p /usr/share/doc/looking-glass-client/"
      - "install -Dm 644 /opt/io.looking-glass.client/client/build/looking-glass-client /usr/bin/looking-glass-client"
      - "install -Dm 644 /opt/io.looking-glass.client/README.md /usr/share/doc/looking-glass-client/README.md"
      - "install -Dm 644 /opt/io.looking-glass.client/LICENSE /usr/share/doc/looking-glass-client/LICENSE"
      - "install -Dm 644 /opt/io.looking-glass.client/AUTHORS /usr/share/doc/looking-glass-client/AUTHORS"
      - "install -Dm 644 /opt/io.looking-glass.client/CONTRIBUTORS /usr/share/doc/looking-glass-client/CONTRIBUTORS"
      - "install -Dm 644 /opt/io.looking-glass.client/resources/lg-logo.svg /usr/share/icons/hicolor/scalable/apps/io.looking-glass.client.svg"
      # vibrant-updater.
      - "git clone https://codeberg.org/vibrantleaf/vibrant-updater.git /opt/org.codeberg.vibrantleaf.vibrant-updater"
      - "(cd /opt/org.codeberg.vibrantleaf.vibrant-updater;git checkout $(git describe --tags '$(git rev-list --tags --max-count=1)'))"
      - "go build -o /usr/bin/vibrant-updater /opt/org.codeberg.vibrantleaf.vibrant-updater/src/vibrant_updater.go"
      - "mkdir -p /usr/share/vibrant-updater/"
      - "install -Dm 644 /opt/org.codeberg.vibrantleaf.vibrant-updater/LICENSE.txt /usr/share/vibrant-updater/LICENSE.en.txt"
      - "install -Dm 644 /opt/org.codeberg.vibrantleaf.vibrant-updater/src/VibrantUpdater.just /usr/share/vibrant-updater/VibrantUpdater.just"
      - "install -Dm 644 /opt/org.codeberg.vibrantleaf.vibrant-updater/src/VibrantUpdater-user.timer /usr/share/vibrant-updater/VibrantUpdater-user.timer"
      - "install -Dm 644 /opt/org.codeberg.vibrantleaf.vibrant-updater/assets/Logo_Circle.svg /usr/share/icons/hicolor/scalable/apps/org.codeberg.vibrantleaf.vibrant-updater.svg"      
  
  # Bluebuild CLI.
  - type: copy
    from: ghcr.io/blue-build/cli:latest
    src: /usr/bin/bluebuild
    dest: /usr/bin/bluebuild

  # Codecs.
  - type: rpm-ostree
    install:
      - "rpmfusion-free-release-tainted"
      - "rpmfusion-nonfree-release-tainted"

  - type: rpm-ostree
    install:
      - "gstreamer1-plugin-libav"
      - "gstreamer1-plugins-bad-free-extras"
      - "gstreamer1-plugins-bad-freeworld"
      - "gstreamer1-plugins-ugly"
      - "gstreamer1-vaapi"
      - "libaacs"
      - "libbdplus"
      - "libbluray"
      - "libdvdcss"

  # Default Flatpaks.
  - type: default-flatpaks
    notify: true
    user: {}
    system:
      install:
        - org.mozilla.firefox
        - org.libreoffice.LibreOffice
        - org.localsend.localsend_app
        - dev.geopjr.Collision
        - org.gnome.World.Secrets
        - com.belmoussaoui.Authenticator
        - com.github.tchx84.Flatseal
        - io.gitlab.adhami3310.Impression
        - ca.edestcroix.Recordbox
        - page.tesk.Refine
        - com.github.marhkb.Pods
        - io.github.dvlv.boxbuddyrs

  # Set GNOME tweaks.
  - type: gnome-extensions
    install:
      - 4655 # Date Menu Formatter
      - 6784 # Wiggle
      - 3733 # Tiling Assistant
      - 7867 # App Grid Wizard
      - 4691 # PiP on top
      - 5940 # Quick Settings Audio Panel

  - type: gschema-overrides
    include:
      - gnome_settings.gschema.override

  - type: bling
    install:
      #- gnome-vrr
      - dconf-update-service
      
  # Get Bluefin Wallpapers.
  - type: copy
    from: ghcr.io/ublue-os/bluefin:stable
    src: /usr/share/backgrounds/bluefin
    dest: /usr/share/backgrounds/bluefin

  # Get Aruroa Wallpapers.
  - type: copy
    from: ghcr.io/ublue-os/aurora:stable
    src: /usr/share/backgrounds/aurora
    dest: /usr/share/backgrounds/aurora
  
  # Cleanning.
  - type: rpm-ostree
    remove:
      - "cmake"
      - "gcc-c++"
      - "libglvnd-devel"
      - "cmake-data"
      - "spice-protocol"
      - "nettle-devel"
      - "binutils-devel"
      - "libXi-devel"
      - "libXinerama-devel"
      - "libXcursor-devel"
      - "libXpresent-devel"
      - "libxkbcommon-x11-devel"
      - "wayland-devel"
      - "wayland-protocols-devel"
      - "libXScrnSaver-devel"
      - "libXrandr-devel"
      - "libdecor-devel"
      #- "pipewire-devel"
      - "pulseaudio-libs-devel"
      - "libsamplerate-devel"
      #- "go"
      - "lutris"
      - "gnome-shell-extension-hotedge"
      - "gnome-shell-extension-bazzite-menu"
      - "gnome-shell-extension-just-perfection"
      - "gnome-shell-extension-compiz-alike-magic-lamp-effect"
      - "gnome-shell-extension-compiz-windows-effect"
      - "rom-properties-gtk3"
      #- "gnome-tweaks"
      #- "firefox"
      #- "firefox-langpacks"
      #- "steamdeck-backgrounds"
      #- mediawriter

  - type: script
    snippets:
      - "chmod 644 /usr/share/applications/looking-glass.desktop"
      - "chmod 644 /usr/share/applications/vibrant-updater.desktop"
      - "chmod +x /usr/bin/bluebuild"
      - "chmod +x /usr/bin/looking-glass-client"
      - "chmod +x /usr/bin/vibrant-updater"
      - "rm -rfv /opt/org.codeberg.vibrantleaf.vibrant-updater"
      - "rm -rfv /opt/io.looking-glass.client"

  # Signing.
  - type: signing
