---
name: morgi-gwyrdd
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest
modules:
  - type: files
    files:
      - source: system
        destination: /

  # virtualisation stack
  - type: rpm-ostree
    repos:
      - "https://copr.fedorainfracloud.org/coprs/hikariknight/looking-glass-kvmfr/repo/fedora-42/hikariknight-looking-glass-kvmfr-fedora-42.repo"
    install:
      - virt-install
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - qemu-kvm
      - virt-manager
      - virt-viewer
      - libguestfs-tools
      - python3-libguestfs
      - virt-top
      - swtpm
      - bridge-utils
      - gnome-boxes
  
  # blue-build cli
  - type: copy
    from: ghcr.io/blue-build/cli:latest-installer
    src: /out/bluebuild
    dest: /opt/bluebuild
  - type: script
    snippets:
      - "mv -v /opt/bluebuild /usr/bin/"
      - "chmod +x /usr/bin/bluebuild"

  # codecs
  - type: rpm-ostree
    install:
      - rpmfusion-free-release-tainted
  - type: rpm-ostree
    install:
      - rpmfusion-nonfree-release-tainted
  - type: rpm-ostree
    install:
      - gstreamer1-plugin-libav
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-ugly
      - gstreamer1-vaapi
      - libaacs
      - libbdplus
      - libbluray
      - libdvdcss

  # cleanup
  - type: rpm-ostree
    remove:
      - gnome-xsession

  # flatpaks
  - type: default-flatpaks
    notify: true
    user: {}
    system:
      install:
        - org.mozilla.firefox
        - org.libreoffice.libreoffice
        - org.localsend.localsend_app
        - org.gnome.Geary
        - dev.geopjr.Collision
        - org.gnome.World.Secrets
        - com.belmoussaoui.Authenticator
        - com.github.tchx84.Flatseal

  # GNOME
  - type: gnome-extensions
    install:
      - 4655
      - 6784
      - 3733
      - 5547
      - 7867
      - 4691
  - type: gschema-overrides
    include:
      - gnome_settings.gschema.override


  # signing    
  - type: signing

