---
name: morgi-gwyrdd
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest
modules:
  - type: files
    files:
      - source: system
        destination: /


  # virtualisation stack
  - type: rpm-ostree
    repos:
      - "https://copr.fedorainfracloud.org/coprs/hikariknight/looking-glass-kvmfr/repo/fedora-42/hikariknight-looking-glass-kvmfr-fedora-42.repo"
    install:
      - virt-install
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - qemu-kvmn
      - virt-manager
      - virt-viewer
      - libguestfs-tools
      - python3-libgeustfs
      - virt-top
      - swtpm
      - gnome-boxes

  
  # blue-build cli
  - type: copy
    from: ghcr.io/blue-build/cli:latest-installer
    src: /out/bluebuild
    dest: /opt/bluebuild
  - type: script
    snippets:
      - "mv -v /opt/bluebuild /usr/lbin/"
      - "chmod +x /usr/bin/bluebuild"

  # flatpaks
  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - 
      remove:
        - org.gnome.eog
    user: {}

  - type: signing

