---
name: morgi-gwyrdd
description: This is just my persoanl fork of bazzite.
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest
modules:
  #- type: filesf
  #   files:
  #    - source: system
  #      destination: /

  # Just Files
  - type: justfiles
    validate: true
    include:
      - morgi-gwyrdd-generic-hostname.just
  
  # Virtualisation Stack
  - type: rpm-ostree
  #  repos:
  #    - "https://copr.fedorainfracloud.org/coprs/hikariknight/looking-glass-kvmfr/repo/fedora-42/hikariknight-looking-glass-kvmfr-fedora-42.repo"
    install:
      - "virt-install"
      - "libvirt-daemon-config-network"
      - "libvirt-daemon-kvm"
      - "edk2-ovmf"
      - "virt-manager"
      - "virt-viewer"
      - "libguestfs-tools"
      - "python3-libguestfs"
      - "virt-top"
      - "swtpm"
      - "bridge-utils"
      - "gnome-boxes"
  #- type: akmods
  #  install:
  #    - "kvmfr"
  - type: rpm-ostree
    install:
     - "cmake"
     - "gcc"
     - "gcc-c++"
     - "libglvnd-devel"
     - "fontconfig-devel"
     - "spice-protocol"
     - "make"
     - "nettle-devel"
     - "pkgconf-pkg-config"
     - "binutils-devel"
     - "libXi-devel"
     - "libXinerama-devel"
     - "libXcursor-devel"
     - "libXpresent-devel"
     - "libxkbcommon-x11-devel"
     - "wayland-devel"
     - "wayland-protocols-devel"
     - "libXScrnSaver-devel"
     - "libXrandr-devel"
     - "dejavu-sans-mono-fonts"
     - "libdecor-devel"
     #- "pipewire-devel"
     - "pulseaudio-libs-devel"
     - "libsamplerate-devel"
  - type: script
    snippets:
      - "git clone --recursive https://github.com/gnif/LookingGlass.git /opt/io.looking-glass.client"
      - "(cd /opt/io.looking-glass.client/;git checkout $(git describe --tags '$(git rev-list --tags --max-count=1)'))"
      - "mkdir -p /opt/io.looking-glass.client/client/build"
      - "(cd /opt/io.looking-glass.client/client/build;cmake -DENABLE_PIPEWIRE=no -DENABLE_LIBDECOR=ON -DCMAKE_INSTALL_PREFIX=/usr ../)"
      - "(cd /opt/io.looking-glass.client/client/build;make)"
      - "(cd /opt/io.looking-glass.clinet/client/build;make install)"
      - "rm -rfv /opt/io.looking-glass.client"
  - type: rpm-ostree
    remove:
     - "cmake"
     - "gcc"
     - "gcc-c++"
     - "libglvnd-devel"
     - "fontconfig-devel"
     - "spice-protocol"
     - "make"
     - "nettle-devel"
     - "pkgconf-pkg-config"
     - "binutils-devel"
     - "libXi-devel"
     - "libXinerama-devel"
     - "libXcursor-devel"
     - "libXpresent-devel"
     - "libxkbcommon-x11-devel"
     - "wayland-devel"
     - "wayland-protocols-devel"
     - "libXScrnSaver-devel"
     - "libXrandr-devel"
     - "libdecor-devel"
     #- "pipewire-devel"
     - "pulseaudio-libs-devel"
     - "libsamplerate-devel"
  
  # Vibrant Updater
  - type: rpm-ostree
    install:
      - "git"
  - type: script
    snippets:
      - "git clone --branch 1.0.12-2025-01-26 https://codeberg.org/vibrantleaf/vibrant-updater.git /opt/org.codeberg.vibrantleaf.vibrant-updater"
      - "curl -Lo /usr/bin/vibrant-updater https://codeberg.org/vibrantleaf/vibrant-updater/releases/download/1.0.12-2025-01-26/vibrant-updater.linux.x86_64.1.0.12-2025-01-26"
      - "chmod +x /usr/bin/vibrant-updater"
      - "mkdir -p /usr/share/vibrant-updater/"
      - "install -Dm 644 /opt/org.codeberg.vibrantleaf.vibrant-updater/LICENSE.txt /usr/share/vibrant-updater/LICENSE.en.txt"
      - "install -Dm 644 /opt/org.codeberg.vibrantleaf.vibrant-updater/src/VibrantUpdater.just /usr/share/vibrant-updater/VibrantUpdater.just"
      - "install -Dm 644 /opt/org.codeberg.vibrantleaf.vibrant-updater/src/VibrantUpdater-user.timer /usr/share/vibrant-updater/VibrantUpdater-user.timer"
      - "rm -rfv /opt/org.codeberg.vibrantleaf.vibrant-updater"
  
  # Bluebuild CLI
  - type: copy
    from: ghcr.io/blue-build/cli:latest
    src: /usr/bin/bluebuild
    dest: /usr/bin/bluebuild
  - type: script
    snippets:
      - "chmod +x /usr/bin/bluebuild"

  # Codecs
  - type: rpm-ostree
    install:
      - "rpmfusion-free-release-tainted"
      - "rpmfusion-nonfree-release-tainted"
  - type: rpm-ostree
    install:
      - "gstreamer1-plugin-libav"
      - "gstreamer1-plugins-bad-free-extras"
      - "gstreamer1-plugins-bad-freeworld"
      - "gstreamer1-plugins-ugly"
      - "gstreamer1-vaapi"
      - "libaacs"
      - "libbdplus"
      - "libbluray"
      - "libdvdcss"

  # Default Flatpaks
  - type: default-flatpaks
    notify: true
    user: {}
    system:
      install:
        - org.mozilla.firefox
        - org.libreoffice.LibreOffice
        - org.localsend.localsend_app
        - dev.geopjr.Collision
        - org.gnome.World.Secrets
        - com.belmoussaoui.Authenticator
        - com.github.tchx84.Flatseal
        - io.gitlab.adhami3310.Impression

  # Set GNOME tweaks
  - type: gnome-extensions
    install:
      - 4655 # Date Menu Formatter
      - 6784 # Wiggle
      - 3733 # Tiling Assistant
      - 7867 # App Grid Wizard
      - 4691 # PiP on top
      - 5940 # Quick Settings Audio Panel
  - type: gschema-overrides
    include:
      - gnome_settings.gschema.override
      
  # Get Bluefin Wallpapers
  - type: copy
    from: ghcr.io/ublue-os/bluefin:stable
    src: /usr/share/backgrounds/bluefin
    dest: /usr/share/backgrounds/bluefin

  # Get Aruroa Wallpapers
  - type: copy
    from: ghcr.io/ublue-os/aurora:stable
    src: /usr/share/backgrounds/aurora
    dest: /usr/share/backgrounds/aurora

# Cleanning
  - type: rpm-ostree
    remove:
      - "lutris"
      - "gnome-shell-extension-hotedge"
      - "gnome-shell-extension-bazzite-menu"
      - "gnome-shell-extension-just-perfection"
      - "gnome-shell-extension-compiz-alike-magic-lamp-effect"
      - "gnome-shell-extension-compiz-windows-effect"
      - "rom-properties-gtk3"
      - "firefox"
      - "firefox-langpacks"
      #- "steamdeck-backgrounds"
      #- mediawriter
      
  # Signing    
  - type: signing
