---
name: morgi-gwyrdd
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest
modules:
  - type: files
    files:
      - source: system
        destination: /


  # virtualisation stack
  - type: copy
    from: ghcr.io/ublue-os/akmods:${KERNEL_FLAVOR}-${FEDORA_MAJOR_VERSION}
    src: rpms
    dest /opt/akmods-rpms
  - type: copy
    from: ghcr.io/ublue-os/akmods-extra:${KERNEL_FLAVOR}-${FEDORA_MAJOR_VERSION}
    src: /rpms
    dest /opt/akmods-rpms
  - type: script
    snippets:
      - "sed -i 's@enabled=0@enabled=1@g' /etc/yum.repos.d/_copr_ublue-os-akmods.repo"
  - type: rpm-ostree
    repos:
      - 'https://copr.fedorainfracloud.org/coprs/hikariknight/looking-glass-kvmfr/repo/fedora-"${FEDORA_MAJOR_VERSION}"/hikariknight-looking-glass-kvmfr-fedora-"${FEDORA_MAJOR_VERSION}".repo'
    install:
      - /opt/akmods-rpms/kmods/*kvmfr*.rpm
       - virt-install
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - qemu-kvmn
      - virt-manager
      - virt-viewer
      - libguestfs-tools
      - python3-libgeustfs
      - virt-top
      - swtpm
      - gnome-boxes
  - type: script
    snippets:
      - 'rm -rfv /opt/akmods-rpms'
  
  
  
  
  # blue-build cli
  - type: copy
    from: ghcr.io/blue-build/cli:latest-installer
    src: /out/bluebuild
    dest: /opt/bluebuild
  - type: script
    snippets:
      - "mv -v /opt/bluebuild /usr/lbin/"
      - "chmod +x /usr/bin/bluebuild"

  # flatpaks
  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - 
      remove:
        - org.gnome.eog
    user: {}

  - type: signing

