#!/usr/bin/env bash
if [ -n "$system_type" ]
then
  echo "DEBUG: Using the $system_type system type. "
else
    zenity --info  --title="Waydroid Settup Wizard" --text="Set up Waydroid." --ok-label="Start."
    choice=$(zenity --list \
      --title="Waydroid Settup Wizard" \
      --text="Select a System type" \
      --column="Option" --height=300 \
      "VANILLA" "FOSS" "GAPPS")
    case "$choice" in
    "VANILLA") system_type="VANILLA" ;;
    "FOSS") system_type="FOSS" ;;
    "GAPPS") system_type="GAPPS" ;;
    *) echo "No valid selection made." ;;
    esac
fi
(
echo "10" ; sleep 1
echo "Initalising Waydroid ..."
pkexec waydroid init --force \
  --system_channel https://ota.waydro.id/system \
  --vendor_channel https://ota.waydro.id/vendor \
--system_type $system_type
echo "20" ; sleep 1
echo "Downloading F-Droid ..." ; sleep 1
mkdir -p ~/.cache/waydroid/
curl -Lo ~/.cache/waydroid/F-Droid.apk.asc https://f-droid.org/F-Droid.apk.asc
curl -Lo ~/.cache/waydroid/F-Droid.apk https://f-droid.org/F-Droid.apk
echo "30" ; sleep 1
echo "Verifying F-Droid Download ..." ; sleep 1
gpg --keyserver keyserver.ubuntu.com --recv-key 37D2C98789D8311948394E3E41E7044E1DBA2E89
gpg --verify ~/.cache/waydroid/F-Droid.apk.asc ~/.cache/waydroid/F-Droid.apk
echo "40" ; sleep 1
echo "Installing F-Droid into Waydroid ..." ; sleep 1
pkexec waydroid container start & > /dev/null 2>&1
waydroid app install  ~/.cache/waydroid/F-Droid.apk
echo "50" ; sleep 1
echo "Fininshed Installing F-Droid into Waydroid"
echo "60" ; sleep 1
echo "Cleaning up..." ; sleep 1
gpg --delete-secret-key 37D2C98789D8311948394E3E41E7044E1DBA2E89
rm -rfv ~/.cache/waydroid
echo "100" ; sleep 1
) |
zenity --progress --title="Waydroid Settup Wizard" --text="Initalising Waydroid ..." --percentage=0
if [ "$?" = -1 ]
then
zenity --error --text="Waydroid Settup Canceled."
fi
if [ "$system_type" = "GAPPS" ]
then
  zenity --info  --title="Waydroid Settup Wizard" --text="Read The Waydroid FAQ For How TO Get Google Play Certifcation Working Press OK After You Have Completed these step."
  xdg-open "https://docs.waydro.id/faq/google-play-certification"
  pkexec waydroid container restart & > /dev/null 2>&1
  zenity --info  --title="Waydroid Settup Wizard" --text="Waydroid Setup Done!"
  cp -f /usr/share/applications/sharkfin-waydroid-utils-setup-wizard.desktop ~/.local/share/applications
  echo "NoDisplay=true" | tee -a ~/.local/share/applications/sharkfin-waydroid-utils-setup-wizard.desktop
else
  zenity --info  --title="Waydroid Settup Wizard" --text="Waydroid Setup Done!"
  cp -f /usr/share/applications/sharkfin-waydroid-utils-setup-wizard.desktop ~/.local/share/applications
  echo "NoDisplay=true" | tee -a ~/.local/share/applications/sharkfin-waydroid-utils-setup-wizard.desktop
  fi