#!/usr/bin/env bash
set -euxo pipefail
if ! command -v waydroid &> /dev/null
then
    echo "Error: waydroid is not installed." >&2
    exit 1
fi
if ! command -v zenity &> /dev/null
then
    echo "Error: zenity is not installed." >&2
    exit 1
fi
if ! command -v curl &> /dev/null
then
    echo "Error: zenity is not installed." >&2
    exit 1
fi
if ! command -v pkexec &> /dev/null
then
    echo "Error: zenity is not installed." >&2
    exit 1
fi
if [ -n "$system_type" ]
then
  echo "DEBUG: Using the $system_type system type. "
else
  advanced_options_check=$(zenity --info --title "Waydroid Setup Wizard" \
    --text 'Set up Waydroid.' \
    --ok-label Start \
    --extra-button "Advanced Options")
  if [ "$advanced_options_check" = "Advanced Options" ]
  then
    choice=$(zenity --list \
      --title="Waydroid Setup Wizard" \
      --text="Advanced Options" \
      --column="Option" --height=400 \
      "Do not automaticly install F-Droid" "Set a custom system channel" "Set a custom vendor vhannel")
    case "$choice" in
    "Do not automaticly install F-Droid") fdroid="no" ;;
    "Set a custom system channel") custom_system_channel="yes" ;;
    "Set a custom vendor channel") custom_vendor_channel="yes" ;;
    *) echo "No valid selection made." ;;
    esac
  fi
  if [$ custom_system_channel = "yes"]
  then
    system_channel=$(zenity --entry \
      --title="Waydroid Setup Wizard \
      --text="Enter Your Custom System Channel" \
      --entry-text="https://ota.waydro.id/system")
  else
    system_channel="https://ota.waydro.id/system"
  fi
  if [$ custom_vendor_channel = "yes"]
  then
  vendor_channel=$(zenity --entry \
      --title="Waydroid Setup Wizard \
      --text="Enter Your Custom Vendor Channel" \
      --entry-text="https://ota.waydro.id/vendor")
  else
    vendor_channel="https://ota.waydro.id/vendor"
  fi
  zenity --info  --title="Waydroid Setup Wizard" --text="Set up Waydroid." --ok-label="Start."
    choice=$(zenity --list \
      --title="Waydroid Setup Wizard" \
      --text="Select a System type" \
      --column="Option" --height=400 \
      "VANILLA" "FOSS" "GAPPS")
    case "$choice" in
    "VANILLA") system_type="VANILLA" ;;
    "FOSS") system_type="FOSS" ;;
    "GAPPS") system_type="GAPPS" ;;
    *) echo "No valid selection made." ;;
    esac
fi
(
echo "10" ; sleep 1
echo "Initalising Waydroid ..."
pkexec waydroid init --force \
  --system_channel $system_channel \
  --vendor_channel $vendor_channel \
--system_type $system_type
if ! [ "$fdroid" = "no"" ]
then
  echo "20" ; sleep 1
  echo "Downloading F-Droid ..." ; sleep 1
  mkdir -p ~/.cache/waydroid/
  curl -Lo ~/.cache/waydroid/F-Droid.apk.asc https://f-droid.org/F-Droid.apk.asc
  curl -Lo ~/.cache/waydroid/F-Droid.apk https://f-droid.org/F-Droid.apk
  echo "30" ; sleep 1
  echo "Verifying F-Droid Download ..." ; sleep 1
  gpg --keyserver keyserver.ubuntu.com --recv-key 37D2C98789D8311948394E3E41E7044E1DBA2E89
  gpg --verify ~/.cache/waydroid/F-Droid.apk.asc ~/.cache/waydroid/F-Droid.apk
  echo "40" ; sleep 1
  echo "Installing F-Droid into Waydroid ..." ; sleep 1
  pkexec waydroid container start & > /dev/null 2>&1
  waydroid app install  ~/.cache/waydroid/F-Droid.apk
  echo "50" ; sleep 1
  echo "Fininshed Installing F-Droid into Waydroid"
  echo "60" ; sleep 1
  echo "Cleaning up..." ; sleep 1
  gpg --delete-secret-key 37D2C98789D8311948394E3E41E7044E1DBA2E89
 rm -rfv ~/.cache/waydroid
fi
echo "100" ; sleep 1
) |
zenity --progress --title="Waydroid Setup Wizard" --text="Initalising Waydroid ..." --percentage=0
if [ "$system_type" = "GAPPS" ]
then
  zenity --info  --title="Waydroid Setup Wizard" --text="Read The Waydroid FAQ For How TO Get Google Play Certifcation Working Press OK After You Have Completed these step."
  xdg-open "https://docs.waydro.id/faq/google-play-certification"
  pkexec waydroid container restart & > /dev/null 2>&1
fi
if [ -f  /usr/share/applications/sharkfin-waydroid-utils-setup-wizard.desktop ]
  cp -f /usr/share/applications/sharkfin-waydroid-utils-setup-wizard.desktop ~/.local/share/applications
  echo "NoDisplay=true" | tee -a ~/.local/share/applications/sharkfin-waydroid-utils-setup-wizard.desktop
fi
zenity --info  --title="Waydroid Setup Wizard" --text="Waydroid Setup Done!"
if [ "$?" = -1 ]
then
zenity --error --text="Waydroid Setup Canceled."
fi
