#!/usr/bin/env bash
read -t 10 -p "Press Enter to continue within 10 seconds..." input
if [ $? -ne 0 ] || [ "$input" != "" ]
then
   echo "Exiting."
    exit 0
fi
pkexec waydroid session stop
pkexec waydroid container stop

for file in ~/.local/share/applications/waydroid.*.desktop
do
  echo NoDisplay=true |  tee -a  "$file"
done
