FROM ghcr.io/ublue-os/ubuntu-toolbox:latest
RUN apt update
RUN apt upgrade -y
RUN apt remove -y --purge --auto-remove nano vim vim-common
RUN add-apt-repository ppa:maveonair/helix-editor
RUN apt update
RUN apt install -y helix
