name: Build Borealis Stable Images
on:
  schedule:
    - cron:
        "0 8 * * *" # build at 0800 UTC everyday
        # (3 hours & 10 minute's after the lasted stable bluefin build starts building)
  push:
    paths-ignore:
      - "**.md"
      - "**.txt"
      - ".forgejo/*"
      - ".devcontainer/*"
      - ".github/*"
      - ".github/workflows/*"
      - ".github/CODEOWNERS"
      - ".github/dependabot.yml"
      - ".gitignore"
      - "**.gitkeep"
      - ".justfile"
      - "Justfile"
      - ".woodpecker/*"
      - "Conatinerfile/*"
      - "Conatinerfile/sharkfin/*"
      - "Conatinerfile/sharkfin-dx/*"
      - "Conatinerfile/sharkfin-nvidia/*"
      - "Conatinerfile/sharkfin-dx-nvidia/*"
      - "recipes/sharkfin.recipe.d/sharkfin.recipe.yaml"
      - "recipes/sharkfin.recipe.d/sharkfin-nvidia.recipe.yaml"
      - "recipes/sharkfin.recipe.d/sharkfin-dx.recipe.yaml"
      - "recipes/sharkfin.recipe.d/sharkfin-dx-nvidia.recipe.yaml"
      - "recipes/sharkfin.recipe.d/sharkfin-tkg.recipe.yaml"
      - "recipes/borealis.recipe.d/borealis.recipe.yaml"
      - "recipes/borealis.recipe.d/borealis-nvidia.recipe.yaml"
      - "recipes/borealis.recipe.d/borealis-dx.recipe.yaml"
      - "recipes/borealis.recipe.d/borealis-dx-nvidia.recipe.yaml"
      - "recipes/sharkbox.recipe.d/sharkbox.recipe.yaml"
      - "recipes/shetland.recipe.d/shetland.recipe.yaml"
      - "recipes/shared.modules.d/17-gschema-overrides.yaml"
      - "recipes/sharkfin.modules.d/*"
      - "recipes/shetland.modules.d/*"
      - "recipes/sharkbox.modules.d/*"
      - "files/gschema-overrides/*"
      - "files/scripts/sharkfin/*"
      - "files/scripts/shetland/*"
      - "files/scripts/sharkbox/*"
      - "files/system/sharkfin/*"
      - "extras/toolboxes/*"
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - "borealis.recipe.d/borealis.recipe.yaml"
          - "borealis.recipe.d/borealis-nvidia.recipe.yaml"
          - "borealis.recipe.d/borealis-dx.recipe.yaml"
          - "borealis.recipe.d/borealis-dx-nvidia.recipe.yaml"
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.9
        env:
          MOK_PRIV: ${{ secrets.MOK_PRIV }}
          MOK_DER: ${{ secrets.MOK_DER }}
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
          use_cache: true
          rechunk: true
