FROM quay.io/centos-bootc/centos-bootc:10s
RUN dnf update --refresh -y
RUN dnf install --refresh -y git binutils coreutils curl tar zstd cmake make gcc g++
RUN mkdir -p /source/org.box86.box64
RUN git clone https://github.com/ptitSeb/box64.git /source/org.box86.box64
WORKDIR /source/org.box86.box64
RUN cmake  -D ARM_DYNAREC=ON -D CMAKE_BUILD_TYPE=RelWithDebInfo -D BOX32=ON -D BOX32_BINFMT=ON /source/org.box86.box64
RUN make -j4
RUN dnf remove git binutils curl tar zstd make gcc g++
RUN rm -rf /var/cache/* /tmp/*